### ISSUE TITLE
React App: missing mostReadable in tinycolor

### ISSUE THREAD

**Issue by andrashee** [quillforms/quillforms#102] opened 2023-01-22 08:32 UTC
**Describe the bug**

I followed the getting started guide and added it to a new react app using vite.

When I want to compile it, I get the following error:

```✘ [ERROR] No matching export in "node_modules/tinycolor2/esm/tinycolor.js" for import "mostReadable"

    node_modules/@quillforms/utils/build-module/normalize-icon-object.js:8:31:
      8 │ import { default as tinycolor, mostReadable } from 'tinycolor2';
        ╵                                ~~~~~~~~~~~~

/Users/andrashee/code/public/survey/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/@quillforms/utils/build-module/normalize-icon-object.js:8:31: ERROR: No matching export in "node_modules/tinycolor2/esm/tinycolor.js" for import "mostReadable"
```

I tried to fix the tinycolor2 dependency to the same version as you use in the @quillforms/renderer-core package.
Any ideas?

Here my package.json
```
{
	"name": "survey",
	"private": true,
	"version": "0.0.0",
	"scripts": {
		"dev": "vite",
		"serve": "$npm_execpath run dev",
		"build": "tsc && vite build",
		"preview": "vite preview"
	},
	"dependencies": {
		"@quillforms/react-renderer-utils": "^3.0.1",
		"@quillforms/renderer-core": "^3.0.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"tinycolor2": "^1.4.2"
	},
	"devDependencies": {
		"@types/react": "^18.0.21",
		"@types/react-dom": "^18.0.6",
		"@vitejs/plugin-react": "^2.1.0",
		"typescript": "^4.6.4",
		"vite": "^3.1.0"
	}
}
```

Thanks!

**Comment by mdmag** [comment] 2023-01-23 19:09
@andrashee Thanks for reporting this issue.
Let me investigate this!

**Comment by etrpekson99** [comment] 2023-02-01 09:52
@mdmag any updates on this? thanks!

**Comment by AgrPaavan** [comment] 2023-02-03 17:31
> 

I am facing the same issue. Is there an update on how I can fix the issue?

**Comment by mdmag** [comment] 2023-02-04 16:03
@Kevinwochan, 

Thanks for the PR.
I am going to accept it and release a new version today. 
Actually, I was planning to remove totally the usage of mostReadable from tinyColor2 since there is no need for it currently.

**Comment by mdmag** [comment] 2023-02-04 22:35
@andrashee  @AgrPaavan @etrpekson99 @Kevinwochan,
Hey folks,
The issue should have been fixed now.
Please update these packages in your package.json as following:
```
 "@quillforms/react-renderer-utils": "3.1.0",
 "@quillforms/renderer-core": "3.1.0"
```

And let me know please if the issue has been fixed or not!

**Comment by AgrPaavan** [comment] 2023-02-04 23:20
I can confirm that the issue has been resolved. Thank you for the help @mdmag. I think the issue can be closed for now.

**Closed** 2023-02-05 08:59 UTC
